### ISSUE TITLE
add subcommand 'control' to k3 list

### ISSUE THREAD

**Issue by moosq** [nokia/ntt#162]
**Is your feature request related to a problem? Please describe.**
Users want to know which ttcn-3 modules contain control parts. This information could be used to directly address control parts for execution.
**Describe the solution you'd like**
To achieve this `k3 list` command has to be extended with following sub-command:

`k3 list control`

In case control parts are detected following output is generated:

 ```
<module A>.control
<module B>.control
 ```

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by 5nord** [comment]
The nouns of the list command are in plural form (modules, imports, tests). I would suggest to name the sub-command in plural form as well: `k3 list controls`.

We already can list modules, imports and tests. In the future I could imagine to extend the list command further: `k3 list consts`, `k3 list modulepars`, ...  Wouldn't it make sense to change your proposal to something like `k3 list functions`? A user could list control functions like this:

        $ k3 list functions | grep -w control
        $ k3 list functions -r control

**Comment by moosq** [comment]
As `control` is similar to testcases an object(function) which can be executed from an external entity I'd stay with `controls`, i.e.
```
k3 list controls
```
