### ISSUE TITLE
TTCN-3 language server didn't automatically recognize ttcn3 files in the opened folder

### ISSUE THREAD

**Issue by hhk0571** [nokia/ntt#171]
**Describe the bug**
TTCN-3 language server didn't automatically recognize ttcn3 files in the opened folder.
The environment I am working on are as below:
- OS: Windows
- IDE: VS Code
- Terminal: git-bash (MINGW64 installed)

**To Reproduce**
1. Install VS Code, git-bash, and MINGW64, integrated git-bash to VS Code by setting "terminal.integrated.shell.windows"
2. In VS Code, install TTCN-3 extension
3. In VS Code, enable ttcn3 language server
4. In VS Code, open ttcn3 project folder
5. wait for a while, run command palette "TTCN-3: show language server status" 

**Expected behavior**
All known ttcn3 files shall be shown, but the step 5 above show empty ttcn3 files list.
After I manually open one ttcn3 file, and run "TTCN-3: show language server status" again, this time it shows the opened ttcn3 file as known file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Wind10
 - IDE: VS Code
 - Terminal: git-bash (MINGW64 installed)

**Additional context**
I developed python script to search all ttcn3 files and put them into the test suite manifest file -- package.yml, the ttcn3 "go to definition" can work.

**Comment by 5nord** [comment]
The [latest release](https://github.com/nokia/ntt/releases/tag/v0.7.0) brings some improvements regarding test suite management.  However it's not perfect, yet. Every opened folder is recognized as independent test suite.
Could you check if the update helps solving your problem?

Should you have dependencies between directories, a manifest file is easiest way to tell the language server what module belong together. Could you maybe show me what our package.yml looks like?
