### ISSUE TITLE
Document how to use language server with Sublime

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#201]
We provide information how to configure Visual Studio Code or Vim: https://github.com/nokia/ntt/blob/gh-pages/editors.md
Would ne nice, if we could add some examples for Sublime, also.

**Comment by sshiv5768** [comment]
Hi, @5nord I want to work on this issue, is it still open ?

**Comment by 5nord** [comment]
This would be great and yes, the issue is still open!
