### ISSUE TITLE
Document how to use language server with CLion

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#202]
We provide information how to configure Visual Studio Code or Vim: https://github.com/nokia/ntt/blob/gh-pages/editors.md
Would ne nice, if we could add some examples for CLion, also.

**Comment by kmoberg** [comment]
@5nord NTT is written in GOlang so wouldn't [GoLand](https://www.jetbrains.com/go) make more sense than CLion (even though it's the same plugin architecture)?
