### ISSUE TITLE
Trailing newlines get swallowed

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#641]
The new pretty printer does not output any newlines at the end of a file.

**Description**

The `CanonicalPrinter` defined in `ttcn3/v2/printer` should output a single newline character (`\n`) for every one or more line break (e.g. `\r\n\r\n`) in the input source.  
The current implementation however does not output any newlines characters for the last token.

**To Reproduce**
I've prepared a test [here](https://github.com/nokia/ntt/blob/master/ttcn3/v2/printer/printer_test.go#L19). It is currently skiped, to execute this test:
1. Remove `skip` from linked test.
2. Run test.

```
$ go test -run 'TestSimpleFormatter/TestSimpleFormatter#02'
--- FAIL: TestSimpleFormatter (0.00s)
    --- FAIL: TestSimpleFormatter/TestSimpleFormatter#02 (0.00s)
        printer_test.go:76: 
            	Error Trace:	printer_test.go:76
            	Error:      	Not equal: 
            	            	expected: "foo;\n"
            	            	actual  : "foo;"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,2 +1 @@
            	            	 foo;
            	            	-
            	Test:       	TestSimpleFormatter/TestSimpleFormatter#02
FAIL
exit status 1
FAIL	github.com/nokia/ntt/ttcn3/v2/printer	0.003s

```

**Expected behavior**

A trailing newline should not disappear. Examples:

        input: "foo;\n\n\n\n",  want: "foo;\n"
        input: "//foo", want: "//foo"
        input: "//foo\n", want: "//foo\n"

Alternatively I think it would be okay if the last token always has a trailing newline. Examples:

        input: "foo;\n\n\n\n",  want: "foo;\n"
        input: "//foo", want: "//foo\n"
        input: "//foo\n", want: "//foo\n"

**Comment by nitinNT** [comment]
Hi @5nord , I'm beginner to go lang and i have read the documentation for this project and this project seems interesting to me. Can you please guide me to get started with this issue ?

**Comment by 5nord** [comment]
I am happy to hear that :relaxed:

I'd suggest you follow the steps described in the [contribution guide](https://github.com/nokia/ntt/blob/master/CONTRIBUTING.md#contributing-code). When something's unclear you may ask just here in the comments, if you like.

When you're ready with setting up your go environment, we can discuss the issue itself. Sound good?

**Comment by nitinNT** [comment]
yes, thanks

**Comment by nitinNT** [comment]
@5nord i have completed setup for this project. we can discuss this issue.

**Comment by nitinNT** [comment]
@5nord i litle bit understood this issue do i need to add case in `Scan` function present in `scanner.go` file for this case ?

**Comment by 5nord** [comment]
@nitinNT: I added some details to the issue. The scanner.go skips over whitespaces and newlines on purpose. I think fixing in printer.go should be the best way to go.

**Comment by 5nord** [comment]
@nitinNT: I have a very bad conscience, because my feature "accidentally" fixed the issue you were working on.
I am very sorry and I hope you did not put too much work into it already :/

Can I find maybe another issue you're interested in? I promise I won't fix it ;)

**Comment by nitinNT** [comment]
@5nord : No problem, I was looking into printer.go file only and trying to understand the flow by executing to through each line (debugger). Yes, i'm interested for different issues i will try to more understand and solve issue. In fact, i will also look to your PR for this issue like how you fixed issue.

thanks
