### ISSUE TITLE
Allow identical enumeration values

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#653]
We should allow identical enumeration values.

For technical reasons is not supported, yet:
```
ntt -i
ntt dev (none, unknown)
>> type enumerated U { E }
>> type enumerated V { E }
Error: can't add key E, name aleady exists as U.E
```

_Originally posted by @5nord in https://github.com/nokia/ntt/pull/637#pullrequestreview-1135229586_

**Comment by UrbanskiDawid** [comment]
https://github.com/nokia/ntt/pull/685
