### ISSUE TITLE
Incorrect lint error on nested select/case statements

### ISSUE THREAD

**Issue by cojac1** [nokia/ntt#688]
**Describe the bug**
While testing possiblilitiy of using ntt for static code verification (we still use K3 v3 ttcn3Linter tool) i noticed issue with nested select/case statements
All other select/case are properly validated

**To Reproduce**

module TestLinter {

	function f_testLinter() {
        var charstring v_first, v_second;
        select (v_first) {
            case ("first_A") {
            }
            case ("first_B") {
                select (v_second) {
                    case ("second_A") {
                    }
                    case ("second_B") {
                    }
                    case else {
                    }
                }
            }
            case else {
            }
        }
    }
}

ntt lint TestLinter.ttcn3
TestLinter.ttcn3:4:9: error: missing case else in select statement
1 issue found.

**Expected behavior**
No error

**Screenshots**
-

**Additional context**
Needs in config:
require_case_else: true

**Possible fixes**
-

**Comment by 5nord** [comment]
Thanks for the report, cojac1 😊
