### ISSUE TITLE
Discover all the TTCN-3 files!

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#709]
When I am opening a single directory with TTCN-3 files, language server features which involve multiple files, like 'go to definition', do not work properly.

That is because ntt only considers files specified by a testsuite configuration. If there's no configuration file, only manually opened files are known.
 
**Suggestion**

The function `project.Discover` should be extended to load all TTCN-3 files it can find during traversal.

**Comment by JingjianSun** [comment]
@5nord Hello! In which version will this issue be fixed, and when will the version be released? Thanks a lot!

**Comment by 5nord** [comment]
I am sorry, I totally forgot about this issue. Must have gotten lost during my preparations for parental leave. 😶‍🌫️

Next week I will give you an update.

**Comment by JingjianSun** [comment]
Thanks again!

> I am sorry, I totally forgot about this issue. Must have gotten lost during my preparations for parental leave. 😶‍🌫️
> 
> Next week I will give you an update.

Thanks again!
