### ISSUE TITLE
Python API for NTT

### ISSUE THREAD

**Issue by 0xmojo** [nokia/ntt#99]
To control ntt/k3 from Python a wrapper API is desired. Such an API wrapper can be looking 
like this:
```
from k3 import K3

k3 = K3("directory")

testcases = k3.list()
env = k3.show()

startup a new k3 instance:

p = k3.run()
```
and so on...

**Comment by 0xmojo** [comment]
@5nord  What do you think?

**Comment by 5nord** [comment]
There are a couple of minor issues:
* k3 commands allow a directory or a list of files to specify the test suite. This should be reflected in the library
* k3 list can list anything imports, tests, modules, ... . The list method should have a more specific name, like `tests`.

How do you find if the python library would look similar to the [ntt-library](internal/ntt):

```python
from ntt import Suite
suite = Suite("file1", "file2", "file3") # arguments could also be a directory or even empty.
name = suite.name()
sources = suite.sources()
imports = suite.imports()
timeout = suite.timeout()
tests = suite.tests()
env = suite.environ() # key/value pair of `k3 show ... -- env`
hook = suite.testHook()
config = suite.config() # Content of K3_PARAMETERS_FILE
```

Such an API could be nicely extended in the future with methods like `ast = suite.Parse()`?

However I have know idea how proper error handling in python looks like. Exceptions? 

What would `k3.run()` return? Is this a process?

**Comment by 0xmojo** [comment]
Under which directory should this API wrapper be stored?

**Comment by 5nord** [comment]
I have no idea.
